### ISSUE TITLE
mod does not load

### ISSUE THREAD

**Issue by Karnor** [zakuro9715/CS2-AdvancedSimulationSpeed#1]
Doesn't load and adds the _**sample menu**_ in the cities skylines 2 options menu.

**Comment by zakuro9715** [comment]
Loads correctly for other users. Probably your environment problem. 

To use MOD, exit game after add mod to playset then relaunch.

If you still think it's a MOD problem, provide more information such as screenshots and logs. Developers can't know about your environment without information.
