### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by ben-j69** [zakuro9715/CS2-AdvancedSimulationSpeed#9]
Hello,

installed in game, with the required icon mod.

Nothing showed up in the bottom menu. Same after restarting the game or reloading the save.

Thanks

**Comment by zakuro9715** [comment]
I can't reproduce.

[![Image from Gyazo](https://i.gyazo.com/e5b82074f040b248f07c72f68c22341f.png)](https://gyazo.com/e5b82074f040b248f07c72f68c22341f)

Open `%USERPROFILE%\AppData\LocalLow\Colossal Order\Cities Skylines II\Logs\Modding.log` and check MOD state.

There is too little information in this report

>When reporting a bug, please provide as much information as you can. > 
 -How to reproduce
> -Screenshot
> - Enabled MODs
> - MOD Log: %USERPROFILE%\AppData\LocalLow\Colossal Order\Cities Skylines II\Logs\AdvancedSimulationSpeed.Mod.log
> - Modding Log: %USERPROFILE%\AppData\LocalLow\Colossal Order\Cities Skylines II\Logs\Modding.log
> - UI Log: %USERPROFILE%\AppData\LocalLow\Colossal Order\Cities Skylines II\Logs\UI.log


https://forum.paradoxplaza.com/forum/threads/advancedsimulationspeed.1674316/
